# This is a basic workflow to help you get started with Actions

name: Build and Test Jector

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build-jector:
      # runner images with architectures (variants)
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ 'ubuntu-latest' ]
      name: Build jector

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - name: Checkout Job
          uses: actions/checkout@v3

        - name: Setup Temurin-JDK-19
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin' 
            java-version: '19'

        - name: Compiling jector
          run: ./gradlew --console="verbose" :jector:build

        - name: Compiling jector-monkey
          run: ./gradlew --console="verbose" :jector-monkey:build

        - name: Archive jector
          uses: actions/upload-artifact@v3
          with:
            name: jector-snapshot
            path: jector/build/libs/

    test-doc-generation:
        # a linux runner image with the ndk installed and llvm ready to compile android native binaries
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ 'ubuntu-latest' ]
        name: Generating documentation

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          - name: Checkout Job
            uses: actions/checkout@v3
          
          - name: Setup Oracle-JDK-19
            uses: actions/setup-java@v3
            with:
              distribution: 'temurin' 
              java-version: '19'

          - name: Generate javadoc for jector
            run: chmod +rwx ./gradlew && ./gradlew :jector:generateJavadocJar

          - name: Generate javadoc for jector-monkey
            run: chmod +rwx ./gradlew && ./gradlew :jector-monkey:generateJavadocJar

    test:
        # runner images with architectures (variants)
        runs-on: ${{ matrix.os }}
        needs: build-jector
        strategy:
          matrix:
            os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        name: Testing jector on ${{ matrix.os }} for x86-64

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          - name: Checkout Job
            uses: actions/checkout@v3
          
          - name: Setup Temurin-JDK-19
            uses: actions/setup-java@v3
            with:
              distribution: 'temurin' 
              java-version: '19'
          
          - name: Download jector-SNAPSHOT.jar library
            uses: actions/download-artifact@v3
            with:
              name: jector-snapshot
              path: jector/build/libs/

          - name: Run jector example
            run: ./gradlew :jector-examples:run
